"""added auth

Revision ID: 97c026745830
Revises: 7e48b0e72b2a
Create Date: 2026-05-09 17:43:03.452215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c026745830'
down_revision: Union[str, Sequence[str], None] = '7e48b0e72b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
   # --- UPDATE THESE TWO LINES ---
    op.add_column('users', sa.Column('email', sa.String(), server_default='legacy@awaaz.com', nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(), server_default='legacy_hash', nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
